# Generated by Django 4.0.1 on 2022-01-22 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bincompiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesource',
            name='device',
        ),
        migrations.RemoveField(
            model_name='codesource',
            name='filepath',
        ),
    ]
