# Generated by Django 4.0.1 on 2022-01-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeSource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('filepath', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bincompiler.device')),
            ],
        ),
    ]
