# Generated by Django 4.0.1 on 2022-01-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincompiler', '0002_remove_codesource_device_remove_codesource_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
