# Generated by Django 4.0.1 on 2022-01-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bincompiler', '0003_alter_codesource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesource',
            name='hascompiled',
            field=models.BooleanField(default=False),
        ),
    ]
